# Site
name: 'From Fool to Wise'
description: 'Adventures in Investing, Psychology, and Being Less of a Fool'
logo: 'assets/images/logo.png'
favicon: 'assets/images/Favicon.png'
url:    'https://fooltowise.com'

disqus: 'fooltowise-com'
email: 'fromfooltowise@gmail.com'
mailchimp-list: 'https://fooltowise.us4.list-manage.com/subscribe/post?u=fe5dd068fcfb301e391794c4f&amp;id=af7afcaaa2'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-picture-tag 
  
authors:
    julien:
      name:           Julien Husser
      site:           
      avatar:         assets/images/avatar-jul.png
      bio:            "Father, Husband, Investor, Software Developer, and Tea Enthusiast."
      email:          thisisjulienh@gmail.com
      twitter:        https://twitter.com/SalutNounou

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: julien
      avatar: /assets/images/avatar-min.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10
  

picture: 
    ignore_missing_images: true


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
